dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
install:
  - mvn clean install

script:
  - mvn clean verify
after_success:
  - mvn clean test jacoco:report coveralls:report
